linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unused

linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
  revive:
    rules:
      - name: error-strings
        disabled: true

