FROM golang:1.23 AS builder

ARG ARCH=linux64

# Set Environment Variables
SHELL ["/bin/bash", "-c"]
ENV HOME=/app
ENV CGO_ENABLED=0

WORKDIR /app

# Build Application
COPY . .
RUN NO_DIRTY=true make build
RUN chmod +x /app/build/infracost

# Application
FROM alpine:3.16 AS app
# Tools needed for running diffs in CI integrations
RUN apk --no-cache add bash curl git nodejs npm openssh-client

# The jq package provided by alpine:3.15 (jq 1.6-rc1) is flagged as a
# high severity vulnerability, so we install the latest release ourselves
# Reference: https://nvd.nist.gov/vuln/detail/CVE-2016-4074 (this is present on jq-1.6-rc1 as well)
RUN \
    # Install jq-1.6 (final release)
    curl -s -L -o /tmp/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && \
    mv /tmp/jq /usr/local/bin/jq && \
    chmod +x /usr/local/bin/jq

# Install the latest compost version
RUN npm install -g @infracost/compost

WORKDIR /root/

# Scripts are used by CI integrations and other use-cases
COPY scripts/ci/comment.sh /scripts/ci/

COPY --from=builder /app/build/infracost /usr/bin/

ENV INFRACOST_CI_IMAGE=true
ENV INFRACOST_SKIP_UPDATE_CHECK='true'
ENV INFRACOST_LOG_LEVEL=info

ENTRYPOINT ["infracost"]
