FROM cgr.dev/chainguard/go:latest-dev as builder

ENV HOME /app
WORKDIR /app
ENV CGO_ENABLED 0

# Build Application
COPY . .
RUN make deps
RUN NO_DIRTY=true make build
RUN chmod +x /app/build/infracost

# Application
FROM cgr.dev/chainguard/wolfi-base as app
# Tools needed for running diffs in CI integrations
RUN apk --no-cache add ca-certificates bash curl git openssl openssh-client

WORKDIR /root/

COPY --from=builder /app/build/infracost /usr/bin/

ENTRYPOINT [ "infracost" ]
