package schema

type CoreResourceFunc func(*ResourceData) CoreResource

// CoreResource is the new/preferred way to represent provider-agnostic resources that
// support advanced features such as Infracost Cloud usage estimates and actual costs.
type CoreResource interface {
	CoreType() string
	UsageSchema() []*UsageItem
	PopulateUsage(u *UsageData)
	BuildResource() *Resource
}

// ResourceBuilder is used to collect all information required to construct a
// resource that is generated by provider parser and pass it back up to
// top level functions that can supply additional provider-agnostic information
// (such as Infracost Cloud usage estimates) before the resource is built.
type ResourceBuilder struct {
	ResourceData *ResourceData

	// CoreResource is the new/preferred struct for providing an intermediate-object
	// that contains all provider-derived information, but has not yet been built into
	// a Resource.
	CoreResource CoreResource

	// Resource field is provided for backward compatibilty with provider resource builders
	// that have not yet been converted to build CoreResource's
	Resource *Resource
}

// Build create a new Resource from the CoreResource, or (for backward compatibility) returns
// a previously built Resource
func (rb *ResourceBuilder) Build(fetchedUsage *UsageData) *Resource {
	var res *Resource
	if rb.CoreResource != nil {
		u := rb.ResourceData.UsageData
		if fetchedUsage != nil {
			if u == nil {
				u = fetchedUsage
			} else {
				u = u.Merge(fetchedUsage)
			}
		}

		rb.CoreResource.PopulateUsage(u)
		res = rb.CoreResource.BuildResource()
	} else {
		res = rb.Resource
	}

	if res != nil {
		res.ResourceType = rb.ResourceData.Type
		res.Tags = rb.ResourceData.Tags
		res.Metadata = rb.ResourceData.Metadata
	}

	return res
}
