name: Create docker prerelease

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Create docker prerelease
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Free up disk space
        run: |
          # GitHub runners have ~30GB of pre-installed software we don't need
          sudo rm -rf /usr/local/lib/android  # ~12GB Android SDK
          sudo rm -rf /usr/local/.ghcup       # ~6GB Haskell toolchain
          sudo rm -rf /usr/share/dotnet       # ~4GB .NET SDK
          sudo rm -rf /usr/share/swift        # ~3GB Swift toolchain
          sudo rm -rf /opt/hostedtoolcache    # ~6GB cached tool versions

      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPOSITORY }}
          tags: |
            type=edge
          flavor: |
            latest=false

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        id: build_push_docker
        with:
          context: .
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          push: true

      - name: Clean Docker build cache
        run: docker system prune -af --volumes

      - name: Docker meta (CI)
        id: meta-ci
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_ORG }}/${{ secrets.DOCKER_REPOSITORY }}
          tags: |
            type=edge
          flavor: |
            prefix=ci-
            latest=false

      - name: Build and push Docker images (CI)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.ci
          platforms: linux/amd64
          tags: ${{ steps.meta-ci.outputs.tags }}
          push: true
