on:
  release:
    types: [published]

name: Upload post-release assets

jobs:
  update-choco-version:
    if: ${{ !contains(github.ref, '-alpha') && !contains(github.ref, '-beta') }}
    name: Update Chocolatey version
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H 'authorization: Bearer ${{ secrets.POST_RELEASE_TRIGGERS_TOKEN }}' \
            https://api.github.com/repos/infracost/chocolatey-packages/dispatches \
            -d '{"event_type":"infracost_choco"}'

  update-atlantis-versions:
    if: ${{ !contains(github.ref, '-alpha') && !contains(github.ref, '-beta') }}
    name: Update Atlantis versions
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H 'authorization: Bearer ${{ secrets.POST_RELEASE_TRIGGERS_TOKEN }}' \
            https://api.github.com/repos/infracost/infracost-atlantis/dispatches \
            -d '{"event_type":"infracost_atlantis"}'
