name: ARM Template Parser Tests
on: [push, workflow_dispatch]


env:
    PARSER_TEST_PATH: ./internal/providers/arm/parser_test.go

jobs:
    test:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v4
    
        - name: Set up Go 1.22
          uses: actions/setup-go@v4
          with:
              go-version: 1.22
          id: go


        - name: Run Parse Resource Data Test
          run: go test ./internal/providers/arm -run ./internal/providers/arm/parser_test.go

